p1 = "mercure"
p2 = "vénus"
p3 = "terre"
p4 = "mars"
p5 = "jupiter"
p6 = "saturne"
p7 = "uranus"
p8 = "neptune"
b = p5[2]+p7[2]+p7[5]+p3[0]+p1[1]+p6[3]+p3[2] # "pasteur"
c = p1[3:7]     # "cure"
d = p4[0:2] + p4[4:4]    # "ma"
e = len(p4)              # ………………………
f = p1[:e-2] + p1[e+1:]  # "mere"
g = p5[2] + f[1:e]       # "pere"
h = len(b) > len(p8)	                 # ………………………
i = str(len(p1)+len(p2))+str(len(p3))+str(p8.find(p7[3])) # ………………………
j = int(i[0:2]) * (int(i[2]) + 1) # ………………………
k = chr(j)                             # ………………………
l = chr(ord(k) - 2)                    # ………………………
m = (ord(k) % 2) != (ord(l) % 2)    # ………………………
print()